# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- release/*

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: A
  steps:
  - bash: echo "A"
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

- job: B
  steps:
  - bash: echo "B"
  - task: Ant@1
    inputs:
      buildFile: 'build.xml'
      options: 
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'